print('Velkommen til dette program')
print('Indtsat 3 tal, så finder programmet det mindste og det største')
print('tal 1')
tal1=input()
print('tal 2')
tal2=input()
print('tal 3')
tal3=input()
print('Dine tal er '+str(tal1)+' , '+str(tal2) + ' og '+str(tal3))
